set(CTEST_PROJECT_NAME "FairSoft-with-spack")
set(CTEST_SUBMIT_URL "https://cdash.gsi.de/submit.php?project=FairSoft")
set(CTEST_DROP_METHOD "https")
set(CTEST_DROP_SITE "cdash.gsi.de")
set(CTEST_DROP_LOCATION "/submit.php?project=FairSoft")
set(CTEST_DROP_SITE_CDASH TRUE)
